#ifndef AVR_FRAMEWORK_HPP
#define AVR_FRAMEWORL_HPP
#include <adc.hpp>
#include <adc_comp.hpp>
#include <Buffer.hpp>
#include <display7seg.hpp>
#include <external_int.hpp>
#include <interrupt.hpp>
#include <IO.hpp>
//#include <Kernel.hpp>
#include <Kernel_v2.hpp>
#include <liquidcrystal.hpp>
#include <expander_74hc595.hpp>
#include <usart.hpp>
#include <status.hpp>
#include <util/delay.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#endif